//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_ID { get; set; }
        public string Password { get; set; }
        public int User_ID { get; set; }
        public string Login1 { get; set; }
    
        public virtual User User { get; set; }
    }
}
